### ISSUE TITLE
Installation fails at setup.py timezonefinder

### ISSUE THREAD

**Issue by happycamper31** [OpenVoiceOS/OVOS-local-backend#4]
Hello guys,

I'm having an issue installing via pip and couldn't figure out how to solve it. So I hope you guys can help me out here. :-)
Some related info: I already installed mycroft & deepspeech on this Raspberry Pi 4B on Buster 5.10.14-v7l+
My timezone is CET, as that might be related to the issue maybe.
I don't really know what additional info you need, so please hit me up if more is needed.

[RPi_ovos-local-backend.log](https://github.com/OpenVoiceOS/OVOS-local-backend/files/5975735/RPi_ovos-local-backend.log)

Also since I'm not really accustomed to git-procedures I don't know if I submit this correctly or if I should have tried to find help elsewhere. Let me know to improve my git-knowledge ;-)  

BR happycamper

PS: My goal is to run mycroft "homeless" without need of remote connections.

**Comment by JarbasAl** [comment]
python3 is required, i think you are running python2

use `pip3 install`

**Comment by happycamper31** [comment]
Ah, such a "classic"...
Thanks, yeah that worked for me.
I guess you could change the install section to pip3 then ;-9

Sadly I encountered a second issue when starting the backend:
[RPi_ovos-local-server.log](https://github.com/OpenVoiceOS/OVOS-local-backend/files/5976199/RPi_ovos-local-server.log)
I did configuration in between like listed in the readme.

**Comment by JarbasAl** [comment]
please reopen if this is still an issue
